olymps/urls.py
from django.urls import path

from . import views

app_name = 'olymps'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:olymp_id>/', views.detail, name='detail'),
    path('<int:olymp_id>/edit/', views.edit, name='edit'),
    path('<int:olymp_id>/delete/', views.delete, name='delete'),
    path('add/', views.add, name='add'),
    path('<int:olymp_id>/<int:stage_id>/', views.stage_detail, name='stage_detail'),
    path('<int:olymp_id>/<int:stage_id>/edit/', views.stage_edit, name='stage_edit'),
    path('<int:olymp_id>/<int:stage_id>/delete/', views.stage_delete, name='stage_delete'),
    path('<int:olymp_id>/stage_add/', views.stage_add, name='stage_add'),
    path('<int:olymp_id>/stage_add_file/', views.stage_add_file, name='stage_add_file'),
    path('<int:olymp_id>/<int:stage_id>/', views.stage_detail, name='stage_subject_detail'),
    path('<int:olymp_id>/<int:stage_id>/edit/', views.stage_edit, name='stage_subject_edit'),
    path('<int:olymp_id>/<int:stage_id>/delete/', views.stage_delete, name='stage_subject_delete'),
    path('<int:olymp_id>/<int:stage_id>/subject_add/', views.stage_subject_add, name='stage_subject_add'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/', views.stage_subject_detail, name='stage_subject_detail'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/edit/', views.stage_subject_edit, name='stage_subject_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/delete/', views.stage_subject_delete, name='stage_subject_delete'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/', views.stage_subject_parallel, name='stage_subject_parallel'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/export_results', views.export_results, name='export_results'),
    path('<int:olymp_id>/<int:stage_id>/export_results', views.export_results, name='export_results'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/export_for_application', views.export_for_application, name='export_for_application'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/export_participants', views.export_participants, name='export_participants'),
    path('<int:olymp_id>/<int:stage_id>/export_participants', views.export_participants, name='export_participants'),

    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/application_add/', views.application_add, name='application_add'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/application_add_file/', views.application_add_file, name='application_add_file'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/application_add_file_submit/', views.application_add_file_submit, name='application_add_file_submit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/app-<int:app_id>/edit/', views.application_edit, name='application_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/app-<int:app_id>/delete/', views.application_delete, name='application_delete'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/mass_edit/', views.application_mass_edit, name='application_mass_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/mass_edit/', views.application_parallel_mass_edit, name='application_parallel_mass_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/grade_win_set/', views.application_parallel_grade_win_set, name='application_parallel_grade_win_set'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/add_prev_num/', views.application_parallel_add_prev_num, name='application_parallel_add_prev_num'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/add_prev_year/', views.application_parallel_add_prev_year, name='application_parallel_add_prev_year'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
import olymps.views

urlpatterns = [
    path('students/', include('students.urls')),
    path('olymps/', include('olymps.urls')),
    path('admin/', admin.site.urls),
    path('', olymps.views.index)
]

students/urls.py
from django.urls import path

from . import views

app_name = 'students'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:student_id>/', views.detail, name='detail'),
    path('<int:student_id>/edit/', views.edit, name='edit'),
    path('<int:student_id>/edit_submit/', views.edit_submit, name='edit_submit'),
    path('add/', views.add, name='add'),
    path('add_submit/', views.add_submit, name='add_submit'),
    path('add_file/', views.add_file, name='add_file'),
    path('add_file_preview/', views.add_file_preview, name='add_file_preview'),
    path('add_file_submit/', views.add_file_submit, name='add_file_submit'),
    path('add_file_error/', views.add_file_error, name='add_file_error'),
]

olymps/models.py
import datetime

from django.db import models
from django.utils import timezone

import students.models
from django.utils.translation import gettext_lazy as _

class Subject(models.Model):
    name = models.CharField('Название', max_length=255)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'предмет'
        verbose_name_plural = 'предметы'

class Olymp(models.Model):
    name = models.CharField('Название', max_length=255)
    year = models.IntegerField('Год', help_text="Укажите первый год учебного года")

    def __str__(self):
        return self.name + ' ' + str(self.year) + '/' + str(self.year + 1)
    
    class Meta:
        verbose_name = 'олимпиада'
        verbose_name_plural = 'олимпиады'

class OlympStage(models.Model):
    name = models.CharField('Название', max_length=255)
    olymp = models.ForeignKey(Olymp, on_delete=models.PROTECT, verbose_name='Олимпиада')
    num = models.IntegerField('Порядковый номер')

    def __str__(self):
        return self.name + ' ' + str(self.olymp.year) + '/' + str(self.olymp.year + 1)
    
    class Meta:
        verbose_name = 'этап'
        verbose_name_plural = 'этапы'

class OlympStageSubject(models.Model):
    stage = models.ForeignKey(OlympStage, on_delete=models.CASCADE, verbose_name='Этап')
    subject = models.ForeignKey(Subject, on_delete=models.PROTECT, verbose_name='Предмет')
    min_class = models.IntegerField('Минимальный класс')
    max_class = models.IntegerField('Максимальный класс')
    date = models.DateField('Дата проведения', null=True, blank=True)

    def __str__(self):
        return str(self.stage) + ' | ' + self.subject.name
    
    class Meta:
        verbose_name = 'предмет этапа'
        verbose_name_plural = 'предметы этапа'
        unique_together = ('stage', 'subject')

class Grade(models.Model):
    stage_subject = models.ForeignKey(OlympStageSubject, on_delete=models.CASCADE, verbose_name='Предмет')
    parallel = models.IntegerField('Класс')
    gold = models.FloatField('Победитель', null=True, blank=True)
    silver = models.FloatField('Призёр', null=True, blank=True)
    participate = models.FloatField('Проходной балл', null=True, blank=True)

    class Meta:
        verbose_name = 'пороговые баллы'
        verbose_name_plural = 'пороговые баллы'


class Status(models.IntegerChoices):
        WINNER = 1, _('Победитель')
        PRIZER = 2, _('Призёр')
        PARTICIPANT = 3, _('Участник')
        DISQUALIFIED = 100, _('Дискв.')
        ABSENT = 200, _('Неявка')
        __empty__ = _('')

class Application(models.Model):
    stage_subject = models.ForeignKey(OlympStageSubject, on_delete=models.PROTECT, verbose_name='Предмет этапа')
    student = models.ForeignKey(students.models.Student, on_delete=models.PROTECT, verbose_name='Участник')
    group = models.CharField('Класс', max_length=255, null=True, blank=True)
    parallel = models.IntegerField('Класс участия')
    code = models.CharField('Код', max_length=255, null=True, blank=True)
    result = models.FloatField('Баллы', null=True, blank=True)
    status = models.IntegerField('Статус', choices=Status, null=True, blank=True)

    def __str__(self):
        return str(self.student.fio()) + " — " + str(self.stage_subject)

    class Meta:
        verbose_name = 'заявка'
        verbose_name_plural = 'заявки'
        unique_together = ('stage_subject', 'student')

olymps/forms.py
import django.forms as forms
import formset.widgets
from django.core.exceptions import ValidationError

from .models import *
from students.models import *


class OlympForm(forms.ModelForm):
    class Meta:
        model = Olymp
        fields = ['name', 'year']


OlympStageFormset = forms.modelformset_factory(OlympStage, fields=['id', 'num'], extra=0, can_delete=False)


class StageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['olymp'].widget.attrs.update({
            'class' : 'js-chosen'
        })
    
    class Meta:
        model = OlympStage
        fields = ['olymp', 'name', 'num']

class StageSubjectForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].widget = formset.widgets.DateInput()
        try:
            self.fields['subject'].widget.attrs.update({
                'class' : 'js-chosen'
            })
        except:
            pass
        try:
            self.fields['stage'].widget.attrs.update({
                'class' : 'js-chosen'
            })
        except:
            pass

    class Meta:
        model = OlympStageSubject
        fields=['id', 'stage', 'subject', 'min_class', 'max_class', 'date']


StageSubjectsFormset = forms.modelformset_factory(
    OlympStageSubject,
    StageSubjectForm,
    fields=['id', 'min_class', 'max_class', 'date'],
    extra=0,
    can_delete=False
)

class ApplicationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        try:
            self.fields['student'].widget.attrs.update({
                'class' : 'js-chosen'
            })
        except:
            pass
        try:
            self.fields['stage_subject'].widget.attrs.update({
                'class' : 'js-chosen'
            })
        except:
            pass
        try:
            self.fields['parallel'].required = False
        except:
            pass
    
    def clean(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['student'].group and not cleaned_data['group']:
            cleaned_data['group'] = str(cleaned_data['student'].group)
        if cleaned_data['student'].group and not cleaned_data['parallel']:
            cleaned_data['parallel'] = max(cleaned_data['student'].group.num, cleaned_data['stage_subject'].min_class)
        if not cleaned_data['student'].group and not cleaned_data['parallel']:
            raise ValidationError(
                "Невозможно получить параллель ученика."
            )
        
        if cleaned_data['parallel'] < cleaned_data['stage_subject'].min_class or cleaned_data['parallel'] > cleaned_data['stage_subject'].max_class:
            raise ValidationError(
                "Параллель не соответствует предмету."
            )

        return cleaned_data

    class Meta:
        model = Application
        fields = ['id', 'stage_subject', 'student', 'group', 'parallel', 'code', 'result', 'status']

ApplicationFormset = forms.modelformset_factory(
    Application,
    ApplicationForm,
    fields=['id', 'stage_subject', 'student', 'group', 'parallel', 'code', 'result', 'status'],
    extra=0,
    can_delete=True,
)

olymps/templates/olymps/stage/subject/add.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'olymps/style.css' %}" />
        <title>{{ stage }} | Добавление предмета</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <h2 class="head_title">Добавление предмета</h2>
            <form method="post" action="#">
                {% csrf_token %}
                <table>
                    <tbody>
                        {% for inp in form %}
                            <tr>
                                <td class="form_label">{{inp.label}}</td>
                                <td class="form_input_table" style="width: 400px">{{inp}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <br />
                <input type="submit" value="Сохранить" />
            </form>
        </main>
    </body>
</html>

olymps/templates/olymps/stage/subject/detail.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'olymps/style.css' %}" />
        <title>{{ subject }}</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <a href="{% url 'olymps:stage_detail' subject.stage.olymp.id subject.stage.id %}"><button>Назад</button></a>
            <br />
            <br />
            <a href="{% url 'olymps:stage_subject_edit' subject.stage.olymp.id subject.stage.id subject.id %}"><button>Редактировать</button></a>
            <h2 class="head_title">{{ subject }}</h2>
            <h3 class="head_title">{{ subject.stage.name }}</h3>
            <table>
                <tr>
                    <td>Класс:</td>
                    <td class="selected_parallel"><a href="{% url 'olymps:stage_subject_detail' subject.stage.olymp.id subject.stage.id subject.id %}">Все</a></td>
                    
                    {% for i in parallels %}
                    <td><a href="{% url 'olymps:stage_subject_parallel' subject.stage.olymp.id subject.stage.id subject.id i %}">{{ i }}</a></td>
                    {% endfor %}
                </tr>
            </table>
            <h3>Участники</h3>
            <a href="{% url 'olymps:application_add' subject.stage.olymp.id subject.stage.id subject.id %}"><button>Добавить одного</button></a>
            <a href="{% url 'olymps:application_mass_edit' subject.stage.olymp.id subject.stage.id subject.id %}"><button>Редактировать</button></a>
            <a href="{% url 'olymps:application_add_file' subject.stage.olymp.id subject.stage.id subject.id %}"><button>Загрузить из файла</button></a>
            <hr />
            <a href="{% url 'olymps:export_participants' subject.stage.olymp.id subject.stage.id subject.id %}"><button>Экспорт участников</button></a>
            <a href="{% url 'olymps:export_results' subject.stage.olymp.id subject.stage.id subject.id %}"><button>Экспорт результатов</button></a>
            <a href="{% url 'olymps:export_for_application' subject.stage.olymp.id subject.stage.id subject.id %}"><button>Экспорт для заявки</button></a>
            <br />
            <br />
            {% if applications %}
                <table class="list">
                    <thead>
                        <tr>
                            <td class="id_column">ID</td>
                            <td>Ученик</td>
                            <td>Код</td>
                            <td class="id_column">Класс</td>
                            <td class="id_column">Класс участия</td>
                            <td class="id_column">Баллы</td>
                            <td class="id_column">Статус</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for app in applications %}
                            <tr class="list_item" onclick="document.location = '{% url 'olymps:application_edit' subject.stage.olymp.id subject.stage.id subject.id app.id %}'">
                                <td class="id_column">{{app.id}}</td>
                                <td>{{app.student.fio}}</td>
                                <td>{{app.code|default_if_none:""}}</td>
                                <td class="id_column">{{app.group|default_if_none:""}}</td>
                                <td class="id_column">{{app.parallel}}</td>
                                <td class="id_column">{{app.result|default_if_none:""}}</td>
                                <td class="id_column">{{ app.get_status_display }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Участников ещё нет.
            {% endif %}
        </main>
    </body>
</html>

olymps/templates/olymps/stage/subject/edit.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'olymps/style.css' %}" />
        <title>{{ stage_subject }} | Редактирование предмета</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <form method="post" action="{% url 'olymps:stage_subject_delete' subject.stage.olymp.id subject.stage.id subject.id %}">
                {% csrf_token %}
                <input class="del_button" type="submit" value="Удалить" onclick="return confirm('Вы уверены, что хотите удалить?\nДля этого у объекта не должно быть зависимых.')">
            </form>
            <h2 class="head_title">Редактирование предмета</h2>
            <form method="post" action="#">
                {% csrf_token %}
                <table>
                    <tbody>
                        {% for inp in form %}
                            <tr>
                                <td class="form_label">{{inp.label}}</td>
                                <td class="form_input_table" style="width: 400px">{{inp}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <br />
                <button>Сохранить</button>
            </form>
        </main>
        <script>
            $(document).ready(function(){
                $('.js-chosen').chosen({
                    width: '100%',
                    no_results_text: 'Совпадений не найдено',
                });
            });
        </script>
    </body>
</html>

olymps/templates/olymps/stage/subject/parallel.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        {% load l10n %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'olymps/style.css' %}" />
        <title>{{ subject }} | {{ parallel }} класс</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <a href="{% url 'olymps:stage_detail' subject.stage.olymp.id subject.stage.id %}"><button>Назад</button></a>
            <br />
            <br />
            <h2 class="head_title">{{ subject }}</h2>
            <h3 class="head_title">{{ subject.stage.name }}</h3>
            <h3 class="head_title">{{ parallel }} класс</h3>
            <table>
                <tr>
                    <td>Класс:</td>
                    <td><a href="{% url 'olymps:stage_subject_detail' subject.stage.olymp.id subject.stage.id subject.id %}">Все</a></td>
                    
                    {% for i in parallels %}
                    <td{% if i == parallel %} class="selected_parallel"{% endif %}><a href="{% url 'olymps:stage_subject_parallel' subject.stage.olymp.id subject.stage.id subject.id i %}">{{ i }}</a></td>
                    {% endfor %}
                </tr>
            </table>
            <div onclick="$('#grade-select').slideToggle(500);" class="slide-header"><h3><a href="#">Управление баллами</a></h3></div>
            <div id="grade-select" {% if not is_open_grade %}style="display: none;"{% endif %}>
                <form method="post" action="{% url 'olymps:application_parallel_add_prev_year' subject.stage.olymp.id subject.stage.id subject.id parallel %}">
                    {% csrf_token %}
                    Добавить победителей и призёров предыдущего года
                    <button {% if not prev_year %}disabled title="Нет олимпиады с таким названием в предыдущем году!"{% endif %}>Добавить</button>
                </form>
                <br />
                <form method="post" action="{% url 'olymps:application_parallel_add_prev_num' subject.stage.olymp.id subject.stage.id subject.id parallel %}">
                    {% csrf_token %}
                    Добавить участников предыдущего этапа, набравших не менее
                    <input {% if not prev_num %}disabled title="Это первый этап!"{% endif %}type="number" step="any" name="grade-participate" class="num-inp" value="{{grade.participate|unlocalize|default_if_none:""}}" required/>
                    баллов
                    <button {% if not prev_num %}disabled title="Это первый этап!"{% endif %}>Добавить</button>
                </form>
                <br />
                <form method="post" action="{% url 'olymps:application_parallel_grade_win_set' subject.stage.olymp.id subject.stage.id subject.id parallel %}">
                    {% csrf_token %}
                    Сделать победителями от
                    <input type="number" step="any" name="grade-gold" class="num-inp" value="{{grade.gold|unlocalize|default_if_none:""}}" required />
                    баллов,
                    <br />
                    Призёрами от
                    <input type="number" step="any" name="grade-silver" class="num-inp" value="{{grade.silver|unlocalize|default_if_none:""}}" required />
                    баллов
                    <br />
                    <button>Подтвердить</button>
                </form>
            </div>
            <h3>Участники</h3>
            <a href="{% url 'olymps:application_add' subject.stage.olymp.id subject.stage.id subject.id %}"><button>Добавить одного</button></a>
            <a href="{% url 'olymps:application_parallel_mass_edit' subject.stage.olymp.id subject.stage.id subject.id parallel %}"><button>Редактировать</button></a>
            <a href="{% url 'olymps:application_add_file' subject.stage.olymp.id subject.stage.id subject.id %}"><button>Загрузить из файла</button></a>
            <br />
            <br />
            {% if applications %}
            <table class="list">
                <thead>
                    <tr>
                        <td class="id_column">ID</td>
                        <td>Ученик</td>
                        <td>Код</td>
                        <td class="id_column">Класс</td>
                        <td class="id_column">Класс участия</td>
                        <td class="id_column">Баллы</td>
                        <td class="id_column">Статус</td>
                    </tr>
                </thead>
                <tbody>
                    {% for app in applications %}
                        <tr class="list_item" onclick="document.location = '{% url 'olymps:application_edit' subject.stage.olymp.id subject.stage.id subject.id app.id %}'">
                            <td class="id_column">{{app.id}}</td>
                            <td>{{app.student.fio}}</td>
                            <td>{{app.code|default_if_none:""}}</td>
                            <td class="id_column">{{app.group|default_if_none:""}}</td>
                            <td class="id_column">{{app.parallel}}</td>
                            <td class="id_column">{{app.result|default_if_none:""}}</td>
                            <td class="id_column">{{ app.get_status_display }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
                Участников ещё нет.
            {% endif %}
        </main>
    </body>
</html>