olymps/urls.py
from django.urls import path

from . import views

app_name = 'olymps'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:olymp_id>/', views.detail, name='detail'),
    path('<int:olymp_id>/edit/', views.edit, name='edit'),
    path('<int:olymp_id>/delete/', views.delete, name='delete'),
    path('add/', views.add, name='add'),
    path('<int:olymp_id>/<int:stage_id>/', views.stage_detail, name='stage_detail'),
    path('<int:olymp_id>/<int:stage_id>/edit/', views.stage_edit, name='stage_edit'),
    path('<int:olymp_id>/<int:stage_id>/delete/', views.stage_delete, name='stage_delete'),
    path('<int:olymp_id>/stage_add/', views.stage_add, name='stage_add'),
    path('<int:olymp_id>/stage_add_file/', views.stage_add_file, name='stage_add_file'),
    path('<int:olymp_id>/<int:stage_id>/', views.stage_detail, name='stage_subject_detail'),
    path('<int:olymp_id>/<int:stage_id>/edit/', views.stage_edit, name='stage_subject_edit'),
    path('<int:olymp_id>/<int:stage_id>/delete/', views.stage_delete, name='stage_subject_delete'),
    path('<int:olymp_id>/<int:stage_id>/subject_add/', views.stage_subject_add, name='stage_subject_add'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/', views.stage_subject_detail, name='stage_subject_detail'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/edit/', views.stage_subject_edit, name='stage_subject_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/delete/', views.stage_subject_delete, name='stage_subject_delete'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/', views.stage_subject_parallel, name='stage_subject_parallel'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/export_results', views.export_results, name='export_results'),
    path('<int:olymp_id>/<int:stage_id>/export_results', views.export_results, name='export_results'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/export_for_application', views.export_for_application, name='export_for_application'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/export_participants', views.export_participants, name='export_participants'),
    path('<int:olymp_id>/<int:stage_id>/export_participants', views.export_participants, name='export_participants'),

    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/application_add/', views.application_add, name='application_add'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/application_add_file/', views.application_add_file, name='application_add_file'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/application_add_file_submit/', views.application_add_file_submit, name='application_add_file_submit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/app-<int:app_id>/edit/', views.application_edit, name='application_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/app-<int:app_id>/delete/', views.application_delete, name='application_delete'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/mass_edit/', views.application_mass_edit, name='application_mass_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/mass_edit/', views.application_parallel_mass_edit, name='application_parallel_mass_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/grade_win_set/', views.application_parallel_grade_win_set, name='application_parallel_grade_win_set'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/add_prev_num/', views.application_parallel_add_prev_num, name='application_parallel_add_prev_num'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/add_prev_year/', views.application_parallel_add_prev_year, name='application_parallel_add_prev_year'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
import olymps.views

urlpatterns = [
    path('students/', include('students.urls')),
    path('olymps/', include('olymps.urls')),
    path('admin/', admin.site.urls),
    path('', olymps.views.index)
]

students/urls.py
from django.urls import path

from . import views

app_name = 'students'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:student_id>/', views.detail, name='detail'),
    path('<int:student_id>/edit/', views.edit, name='edit'),
    path('<int:student_id>/edit_submit/', views.edit_submit, name='edit_submit'),
    path('add/', views.add, name='add'),
    path('add_submit/', views.add_submit, name='add_submit'),
    path('add_file/', views.add_file, name='add_file'),
    path('add_file_preview/', views.add_file_preview, name='add_file_preview'),
    path('add_file_submit/', views.add_file_submit, name='add_file_submit'),
    path('add_file_error/', views.add_file_error, name='add_file_error'),
]

olymps/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from copy import copy, deepcopy
from django.db.models import Q

from datetime import date
from django.utils import timezone

import pandas as pd
from transliterate import translit

from students.models import *
from .models import *
from .forms import *
import olymps.processing as processing

def index(request):
    olymps_list = Olymp.objects.all()
    context = {'olymps': olymps_list}
    return render(request, 'olymps/index.html', context)

def detail(request, olymp_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stages = olymp.olympstage_set.all().order_by('num')
    context = {
        'olymp' : olymp,
        'stages' : stages
    }
    return render(request, 'olymps/detail.html', context)

def edit(request, olymp_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stages = olymp.olympstage_set.all().order_by('num')
    context = {
        'olymp' : olymp,
        'stages' : stages,
        'form' : OlympForm(instance=olymp),
        'form_stage' : OlympStageFormset(prefix='stage', queryset=stages),
    }

    if request.method == 'POST':
        form = OlympForm(request.POST, instance=olymp)
        formset = OlympStageFormset(request.POST, prefix='stage')
        if form.is_valid() and formset.is_valid():
            try:
                olymp = form.save(commit=True)
                formset.save(commit=True)
                return HttpResponseRedirect(reverse('olymps:detail', args=(olymp.id,)))
            except:
                return HttpResponse("Произошла ошибка")
        else:
            return HttpResponse("Данные некорректны")

    return render(request, 'olymps/edit.html', context)

def delete(request, olymp_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)

    if request.method == 'POST':
        try:
            olymp.delete()
            HttpResponseRedirect(reverse('olymps:index'))
        except:
            return HttpResponse("Произошла ошибка")

    return HttpResponseRedirect(reverse('olymps:index'))

def add(request):
    if request.method == "POST":
        form = OlympForm(request.POST)
        if form.is_valid():
            try:
                olymp = form.save(commit=True)
                return HttpResponseRedirect(reverse('olymps:detail', args=(olymp.id,)))
            except:
                return HttpResponse("Произошла ошибка")
        else:
            return HttpResponse("Данные некорректны")
    else:
        context = {
            'form' : OlympForm(),
        }
        return render(request, 'olymps/add.html', context)

def stage_delete(request, olymp_id, stage_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)

    if request.method == 'POST':
        try:
            stage.delete()
            HttpResponseRedirect(reverse('olymps:index'))
        except:
            return HttpResponse("Произошла ошибка")

    return HttpResponseRedirect(reverse('olymps:stage_detail', args=(olymp_id, stage_id,)))

def stage_add(request, olymp_id):
    if request.method == "POST":
        form = StageForm(request.POST)
        if form.is_valid():
            try:
                stage = form.save(commit=True)
                return HttpResponseRedirect(reverse('olymps:stage_detail', args=(stage.olymp.id, stage.id)))
            except:
                return HttpResponse("Произошла ошибка")
        else:
            return HttpResponse("Данные некорректны")
    else:
        olymp = get_object_or_404(Olymp, pk=olymp_id)
        context = {
            'olymp' : olymp,
            'form' : StageForm(instance=OlympStage(olymp=olymp)),
        }
        return render(request, 'olymps/stage/add.html', context)


def stage_add_file(request, olymp_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    if request.method == "POST":
        try:
            f = request.FILES['file']
            processing.stages_file(f, olymp)
            return HttpResponseRedirect(reverse('olymps:detail', args=(olymp.id,)))
        except:
            return HttpResponse("Произошла ошибка")
    else:
        olymp = get_object_or_404(Olymp, pk=olymp_id)
        context = {
            'olymp' : olymp,
        }
        return render(request, 'olymps/stage/add_file.html', context)

def stage_detail(request, olymp_id, stage_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)
    subjects = stage.olympstagesubject_set.all().order_by('-date', 'subject__name')
    context = {
        'stage' : stage,
        'stage_subjects' : subjects
    }
    return render(request, 'olymps/stage/detail.html', context)

def stage_edit(request, olymp_id, stage_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)
    subjects = stage.olympstagesubject_set.all().order_by('subject__name')
    
    context = {
        'olymp' : olymp,
        'stage' : stage,
        'subjects' : subjects,
        'form' : StageForm(instance=stage),
        'form_subject' : StageSubjectsFormset(prefix='subject', queryset=subjects),
    }

    if request.method == 'POST':
        form = StageForm(request.POST, instance=stage)
        formset = StageSubjectsFormset(request.POST, prefix='subject')
        if form.is_valid() and formset.is_valid():
            try:
                stage = form.save(commit=True)
                formset.save(commit=True)
                return HttpResponseRedirect(reverse('olymps:stage_detail', args=(stage.olymp.id, stage.id,)))
            except:
                return HttpResponse("Произошла ошибка")
        else:
            return HttpResponse("Данные некорректны")

    return render(request, 'olymps/stage/edit.html', context)

def stage_delete(request, olymp_id, stage_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)
    if request.method == 'POST':
        try:
            stage.delete()
            return HttpResponseRedirect(reverse('olymps:detail', args=(olymp_id,)))
        except:
            return HttpResponse('Произошла ошибка')
    else:
        return HttpResponse('Некорректный метод запроса')


def stage_subject_add(request, olymp_id, stage_id):
    if request.method == "POST":
        form = StageSubjectForm(request.POST)
        if form.is_valid():
            try:
                stage_subject = form.save(commit=True)
                return HttpResponseRedirect(reverse('olymps:stage_detail', args=(stage_subject.stage.olymp.id, stage_subject.stage.id)))
            except:
                return HttpResponse("Произошла ошибка")
        else:
            return HttpResponse("Данные некорректны")
    else:
        olymp = get_object_or_404(Olymp, pk=olymp_id)
        stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)
        context = {
            'olymp' : olymp,
            'stage' : stage,
            'form' : StageSubjectForm(instance=OlympStageSubject(stage=stage)),
        }
        return render(request, 'olymps/stage/subject/add.html', context)


def stage_subject_edit(request, olymp_id, stage_id, stage_subject_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)
    subject = get_object_or_404(OlympStageSubject, stage=stage, id=stage_subject_id)
    if request.method == "POST":
        form = StageSubjectForm(request.POST, instance=subject)
        if form.is_valid():
            try:
                stage_subject = form.save(commit=True)
                return HttpResponseRedirect(reverse('olymps:stage_subject_detail', args=(stage_subject.stage.olymp.id, stage_subject.stage.id, stage_subject.id)))
            except:
                return HttpResponse("Произошла ошибка")
        else:
            return HttpResponse("Данные некорректны")
    else:
        olymp = get_object_or_404(Olymp, pk=olymp_id)
        stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)
        context = {
            'subject' : subject,
            'form' : StageSubjectForm(instance=subject),
        }
        return render(request, 'olymps/stage/subject/edit.html', context)


def stage_subject_delete(request, olymp_id, stage_id, stage_subject_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)
    subject = get_object_or_404(OlympStageSubject, stage=stage, id=stage_subject_id)
    if request.method == 'POST':
        try:
            subject.delete()
            return HttpResponseRedirect(reverse('olymps:stage_detail', args=(olymp_id, stage_id)))
        except:
            return HttpResponse('Произошла ошибка')
    else:
        return HttpResponse('Некорректный метод запроса')


def stage_subject_detail(request, olymp_id, stage_id, stage_subject_id):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)
    subject = get_object_or_404(OlympStageSubject, stage=stage, id=stage_subject_id)
    applications = subject.application_set.all().order_by('parallel', 'status', '-result', 'group', 'student__last_name', 'student__first_name', 'student__middle_name')
    context = {
        'subject' : subject,
        'applications' : applications,
        'parallels' : list(range(subject.min_class, subject.max_class + 1)) if subject.min_class <= subject.max_class else None,
    }
    return render(request, 'olymps/stage/subject/detail.html', context)


def stage_subject_parallel(request, olymp_id, stage_id, stage_subject_id, parallel):
    olymp = get_object_or_404(Olymp, pk=olymp_id)
    stage = get_object_or_404(OlympStage, olymp=olymp, id=stage_id)

olymps/templates/olymps/stage/add.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'students/style.css' %}" />
        <title>{{ olymp }} | Создание этапа</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <h2 class="head_title">Создание этапа</h2>
            <form method="post" action="#">
                {% csrf_token %}
                <table>
                    <tbody>
                        {% for inp in form %}
                            <tr>
                                <td class="form_label">{{inp.label}}</td>
                                <td class="form_input_table" style="width: 400px">{{inp}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <br />
                <input type="submit" value="Сохранить" />
            </form>
        </main>
    </body>
</html>

olymps/templates/olymps/stage/add_file.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'olymps/style.css' %}" />
        <title>Добавление этапов из файла</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <h2 class="head_title">{{ olymp }} | Добавление этапов</h2>
            <p>Загрузите заполненный <a href="{% static 'olymps/template_files/Этапы шаблон.xlsx' %}" download>шаблон</a> ниже:</p> 
            <form action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input name="file" type="file" accept=".xlsx,.xls,.csv" required />
                <input type="submit" value="Загрузить">
            </form>
        </main>
    </body>
</html>

olymps/templates/olymps/stage/detail.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'olymps/style.css' %}" />
        <title>{{ olymp }}</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <a href="{% url 'olymps:detail' stage.olymp.id %}"><button>Назад</button></a>
            <br />
            <br />
            <a href="{% url 'olymps:stage_edit' stage.olymp.id stage.id %}"><button>Редактировать</button></a>
            <a href="{% url 'olymps:stage_subject_add' stage.olymp.id stage.id %}"><button>Добавить предмет</button></a>
            
            <h2 class="head_title">{{ stage.olymp }}</h2>
            <h3 class="head_title">{{ stage.name }}</h3>
            <h3>Предметы</h3>
            <a href="{% url 'olymps:export_participants' stage.olymp.id stage.id %}"><button>Экспорт всех участников</button></a>
            <a href="{% url 'olymps:export_results' stage.olymp.id stage.id %}"><button>Экспорт всех результатов</button></a>
            <br />
            <br />
            {% if stage_subjects %}
            <table class="list">
                <thead>
                    <tr>
                        <td class="id_column">ID</td>
                        <td>Предмет</td>
                        <td class="id_column">Классы</td>
                        <td class="id_column">Дата</td>
                    </tr>
                </thead>
                <tbody>
                    {% for stage_subject in stage_subjects %}
                        <tr class="list_item" onclick="document.location = '{% url 'olymps:stage_subject_detail' stage.olymp.id stage.id stage_subject.id %}'">
                            <td class="id_column">{{ stage_subject.id }}</td>
                            <td>{{ stage_subject.subject }}</td>
                            <td>{{ stage_subject.min_class }}-{{ stage_subject.max_class }}</td>
                            <td>
                                {% if stage_subject.date %}
                                    {{ stage_subject.date|date:"d.m.Y" }}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
                Предметов ещё нет.
            {% endif %}
        </main>
    </body>
</html>

olymps/templates/olymps/stage/edit.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'olymps/style.css' %}" />
        <title>{{ stage }} | Редактирование</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <form method="post" action="{% url 'olymps:stage_delete' olymp.id stage.id %}">
                {% csrf_token %}
                <input class="del_button" type="submit" value="Удалить" onclick="return confirm('Вы уверены, что хотите удалить?\nДля этого у объекта не должно быть зависимых.')">
            </form>
            <h2 class="head_title">Редактирование этапа</h2>
            <form method="post" action="#">
                {% csrf_token %}
                <table>
                    <tbody>
                        {% for inp in form %}
                            <tr>
                                <td class="form_label">{{inp.label}}</td>
                                <td class="form_input_table" style="width: 400px">{{inp}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <br />
                <h3>Изменить предметы</h3>
                <table class="list">
                    <thead>
                        <tr>
                            <td>Предмет</td>
                            <td>Мин. кл.</td>
                            <td>Макс. кл.</td>
                            <td>Дата</td>
                        </tr>
                    </thead>
                    <tbody>
                        {{ form_subject.management_form }}
                        {% for f in form_subject %}
                            <tr>
                                {{f.id}}
                                <td class="form_input_table">{{f.instance.subject.name}}</td>
                                <td class="id_column form_input_table">{{f.min_class}}</td>
                                <td class="id_column form_input_table">{{f.max_class}}</td>
                                <td class="id_column form_input_table">{{f.date}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <br />
                <input type="submit" value="Сохранить" />
            </form>
        </main>
    </body>
</html>