olymps/urls.py
from django.urls import path

from . import views

app_name = 'olymps'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:olymp_id>/', views.detail, name='detail'),
    path('<int:olymp_id>/edit/', views.edit, name='edit'),
    path('<int:olymp_id>/delete/', views.delete, name='delete'),
    path('add/', views.add, name='add'),
    path('<int:olymp_id>/<int:stage_id>/', views.stage_detail, name='stage_detail'),
    path('<int:olymp_id>/<int:stage_id>/edit/', views.stage_edit, name='stage_edit'),
    path('<int:olymp_id>/<int:stage_id>/delete/', views.stage_delete, name='stage_delete'),
    path('<int:olymp_id>/stage_add/', views.stage_add, name='stage_add'),
    path('<int:olymp_id>/stage_add_file/', views.stage_add_file, name='stage_add_file'),
    path('<int:olymp_id>/<int:stage_id>/', views.stage_detail, name='stage_subject_detail'),
    path('<int:olymp_id>/<int:stage_id>/edit/', views.stage_edit, name='stage_subject_edit'),
    path('<int:olymp_id>/<int:stage_id>/delete/', views.stage_delete, name='stage_subject_delete'),
    path('<int:olymp_id>/<int:stage_id>/subject_add/', views.stage_subject_add, name='stage_subject_add'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/', views.stage_subject_detail, name='stage_subject_detail'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/edit/', views.stage_subject_edit, name='stage_subject_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/delete/', views.stage_subject_delete, name='stage_subject_delete'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/', views.stage_subject_parallel, name='stage_subject_parallel'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/export_results', views.export_results, name='export_results'),
    path('<int:olymp_id>/<int:stage_id>/export_results', views.export_results, name='export_results'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/export_for_application', views.export_for_application, name='export_for_application'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/export_participants', views.export_participants, name='export_participants'),
    path('<int:olymp_id>/<int:stage_id>/export_participants', views.export_participants, name='export_participants'),

    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/application_add/', views.application_add, name='application_add'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/application_add_file/', views.application_add_file, name='application_add_file'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/application_add_file_submit/', views.application_add_file_submit, name='application_add_file_submit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/app-<int:app_id>/edit/', views.application_edit, name='application_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/app-<int:app_id>/delete/', views.application_delete, name='application_delete'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/mass_edit/', views.application_mass_edit, name='application_mass_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/mass_edit/', views.application_parallel_mass_edit, name='application_parallel_mass_edit'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/grade_win_set/', views.application_parallel_grade_win_set, name='application_parallel_grade_win_set'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/add_prev_num/', views.application_parallel_add_prev_num, name='application_parallel_add_prev_num'),
    path('<int:olymp_id>/<int:stage_id>/<int:stage_subject_id>/<int:parallel>/add_prev_year/', views.application_parallel_add_prev_year, name='application_parallel_add_prev_year'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
import olymps.views

urlpatterns = [
    path('students/', include('students.urls')),
    path('olymps/', include('olymps.urls')),
    path('admin/', admin.site.urls),
    path('', olymps.views.index)
]

students/urls.py
from django.urls import path

from . import views

app_name = 'students'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:student_id>/', views.detail, name='detail'),
    path('<int:student_id>/edit/', views.edit, name='edit'),
    path('<int:student_id>/edit_submit/', views.edit_submit, name='edit_submit'),
    path('add/', views.add, name='add'),
    path('add_submit/', views.add_submit, name='add_submit'),
    path('add_file/', views.add_file, name='add_file'),
    path('add_file_preview/', views.add_file_preview, name='add_file_preview'),
    path('add_file_submit/', views.add_file_submit, name='add_file_submit'),
    path('add_file_error/', views.add_file_error, name='add_file_error'),
]

students/models.py
import datetime

from django.db import models
from django.utils import timezone


class Group(models.Model):
    num = models.IntegerField("Параллель")
    liter = models.CharField("Литера", max_length=2)
    alumnus = models.BooleanField("Выпустился", default=False)

    def __str__(self):
        return str(self.num) + ' ' + self.liter
    
    class Meta:
        unique_together = ('num', 'liter')
        verbose_name = 'класс'
        verbose_name_plural = 'классы'
        ordering = ['num', 'liter']


class Student(models.Model):
    last_name = models.CharField("Фамилия", max_length=200)
    first_name = models.CharField("Имя", max_length=200)
    middle_name = models.CharField("Отчество", max_length=200, null=True, blank=True)
    date_of_birth = models.DateField("Дата рождения", null=True, blank=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Класс")

    def __str__(self):
        return self.last_name + ' ' + self.first_name + \
            (' ' + self.middle_name if self.middle_name else '') + \
            (' ' + str(self.group) if self.group else '')

    def fio(self):
        return self.last_name + ' ' + self.first_name + \
            (' ' + self.middle_name if self.middle_name else '')
    
    class Meta:
        verbose_name = 'ученик'
        verbose_name_plural = 'ученики'

students/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

from datetime import date
from django.utils import timezone

import pandas as pd

from .models import Student, Group

import students.processing as processing


def index(request):
    students_list = Student.objects.exclude(group__alumnus=True).order_by('group__num', 'group__liter', 'last_name', 'first_name', 'middle_name')
    context = {'students': students_list}
    return render(request, 'students/index.html', context)

def detail(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    return render(request, 'students/detail.html', {'student': student})

def edit(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    context = {
        'student' : student,
        'groups_list' : Group.objects.filter(alumnus=False)
    }
    return render(request, 'students/edit.html', context)

def edit_submit(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    processing.edit_student(request, student)
    return HttpResponseRedirect(reverse('students:detail', args=(student_id,)))


def add(request):
    context = { 'groups_list' : Group.objects.filter(alumnus=False)}
    return render(request, 'students/add.html', context)

def add_submit(request):
    student = processing.add_student(request)
    return HttpResponseRedirect(reverse('students:detail', args=(student.id,)))

def add_file(request):
    return render(request, 'students/add_file.html')

def add_file_preview(request):
    context = {
        'students_to_add' : [],
        'groups_to_add' : [],
        'students_to_delete' : [],
        'students_to_update_group' : [],
        'students_to_add_dob' : [],
    }
    try:
        processing.get_students_update_lists(request, context)
        return render(request, 'students/add_file_preview.html', context)
    except:
        return render(request, 'students/add_file_error.html')

def add_file_submit(request):
    try:
        processing.save_students_update_lists(request)
        return HttpResponseRedirect(reverse('students:index'))
    except:
        return HttpResponseRedirect(reverse('students:add_file_error'))

def add_file_error(request):
    return render(request, 'students/add_file_error.html')

students/templates/students/add.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'students/style.css' %}" />
        <title>Добавление ученика</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <h2 class="head_title">Добавление ученика</h2>
            <form action="{% url 'students:add_submit' %}" method="post">
                {% csrf_token %}
                <table class="table_form">
                    <tr>
                        <td>Фамилия:</td>
                        <td><input name="last_name" placeholder="Иванов" required /></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Имя:</td>
                        <td><input name="first_name" placeholder="Иван" required /></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Отчество:</td>
                        <td><input name="middle_name" placeholder="Иванович" /></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Класс:</td>
                        <td><input name="group" list="groups_list" placeholder="5 А" /></td>
                        <td><i>(если класса с данным именем нет, он будет создан)</i></td>
                        <datalist id="groups_list">
                            {% if groups_list %}
                                {% for group in groups_list %}
                                    <option value="{{ group }}"></option>
                                {% endfor %}
                            {% endif %}
                        </datalist>
                    </tr>
                    <tr>
                        <td>Дата рождения:</td>
                        <td><input type="date" name="date_of_birth" /></td>
                        <td></td>
                    </tr>
                </table>
                <br />
                <input type="submit" value="Сохранить">
            </form>
        </main>
    </body>
</html>

students/templates/students/add_file.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'students/style.css' %}" />
        <title>Добавление учеников из файла</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <h2 class="head_title">Добавление учеников</h2>
            <p>Загрузите заполненный <a href="{% static 'students/template_files/Ученики шаблон.xlsx' %}" download>шаблон</a> ниже:</p> 
            <form action="{% url 'students:add_file_preview' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input name="uploaded_students" type="file" accept=".xlsx,.xls" required />
                <input type="submit" value="Загрузить">
            </form>
        </main>
    </body>
</html>

students/templates/students/add_file_error.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'students/style.css' %}" />
        <meta http-equiv="refresh" content="3; URL={% url 'students:index' %}" />
        <title>Добавление учеников из файла</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <p>Произошла ошибка!</p>
        </main>
    </body>
</html>

students/templates/students/add_file_preview.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'students/style.css' %}" />
        <title>Добавление учеников из файла</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <h2 class="head_title">Добавление учеников</h2>
            {% if groups_to_add or students_to_add or students_to_delete or students_to_add_dob or students_to_update_group %}
                <form action="{% url 'students:add_file_submit' %}" method="post">
                    {% csrf_token %}
                    <label><input type="checkbox" name="is_delete" value="Yes" />Удалять отсутствующих учеников <i>(не рекомендуется)</i></label>
                    <br /><br />
                    <input type="submit", value="Применить изменения", style="background-color: #cbffd4; border-color: #bbffc4" />
                </form>
                <p>Проверьте корректность изменений ниже:</p>
                {% if students_to_delete %}
                    <p>Будут <span style="color: red">УДАЛЕНЫ</span> ученики:</p>
                    <table class="list">
                        <thead>
                            <td>ID</td>
                            <td>Фамилия</td>
                            <td>Имя</td>
                            <td>Отчество</td>
                            <td>Класс</td>
                            <td>Дата рождения</td>
                        </thead>
                        {% for user in students_to_delete %}
                            <tr class="list_item_delete">
                                <td>{{ user.id }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.first_name }}</td>
                                <td>
                                    {% if user.middle_name %}
                                        {{ user.middle_name }}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if user.group %}
                                        {{ user.group }}
                                    {% endif %}
                                </td>
                                <td>{{ user.date_of_birth|date:"d.m.Y" }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                    <br />
                    <hr />
                    <br />
                {% endif %}

                {% if students_to_update_group or students_to_add_dob %}
                    <p>Будут обновлены данные об учениках:</p>
                    <table class="list">
                        <thead>
                            <td>ID</td>
                            <td>Фамилия</td>
                            <td>Имя</td>
                            <td>Отчество</td>
                            <td>Класс</td>
                            <td>Дата рождения</td>
                        </thead>
                        {% if students_to_update_group %}
                            {% for user in students_to_update_group %}
                                <tr class="list_item_update">
                                    <td>{{ user.0 }}</td>
                                    <td>{{ user.1 }}</td>
                                    <td>{{ user.2 }}</td>
                                    <td>
                                        {% if user.3 %}
                                            {{ user.3 }}
                                        {% endif %}
                                    </td>
                                    <td style="background-color: yellow;">
                                        <s>
                                            {% if user.4 %}
                                                {{ user.4 }}
                                            {% endif %}
                                        </s>
                                        {% if user.6 %}
                                            {{ user.6 }}
                                        {% endif %}
                                    </td>
                                    <td>{{ user.5|date:"d.m.Y" }}</td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        {% if students_to_add_dob %}
                            {% for user in students_to_add_dob %}
                                <tr class="list_item_update">
                                    <td>{{ user.0 }}</td>
                                    <td>{{ user.1 }}</td>
                                    <td>{{ user.2 }}</td>
                                    <td>
                                        {% if user.3 %}
                                            {{ user.3 }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if user.4 %}
                                            {{ user.4 }}
                                        {% endif %}
                                    </td>
                                    <td style="background-color: #cbffd4;">
                                        {{ user.5|date:"d.m.Y" }}
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </table>
                    <br />
                    <hr />
                    <br />
                {% endif %}

                {% if groups_to_add %}
                    <p>Будут добавлены классы:</p>
                    <table class="list", style="width: 30%">
                        <thead>
                            <td>ID</td>
                            <td>Параллель</td>
                            <td>Литера</td>
                        </thead>
                        {% for group in groups_to_add %}
                            <tr class="list_item_add">
                                <td>-</td>
                                <td>{{ group.num }}</td>
                                <td>{{ group.liter }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                    <br />
                    <hr />
                    <br />
                {% endif %}

                {% if students_to_add %}
                    <p>Будут добавлены ученики:</p>
                    <table class="list">
                        <thead>
                            <td>ID</td>
                            <td>Фамилия</td>
                            <td>Имя</td>
                            <td>Отчество</td>
                            <td>Класс</td>
                            <td>Дата рождения</td>
                        </thead>
                        {% for user in students_to_add %}
                            <tr class="list_item_add">
                                <td>-</td>
                                <td>{{ user.0 }}</td>
                                <td>{{ user.1 }}</td>
                                <td>
                                    {% if user.2 %}
                                        {{ user.2 }}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if user.3 %}
                                        {{ user.3 }}
                                    {% endif %}
                                </td>
                                <td>{{ user.4|date:"d.m.Y" }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            {% else %}
                <p>Изменений нет.</p>
                <a href={% url 'students:add_file' %}>Вернуться</a>
            {% endif %}
        </main>
    </body>
</html>

students/templates/students/detail.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'students/style.css' %}" />
        <title>{{ student }}</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <a href="{% url 'students:edit' student.id %}"><button>Редактировать</button></a>
            <h2 class="head_title">Информация об ученике</h2>
            <div class="student_info">
                <p class="fio">{{ student.last_name }} {{ student.first_name }}{% if student.middle_name %} {{ student.middle_name }}{% endif %}</p>
                <p>
                    {% if student.group %}
                        {{ student.group }}
                    {% else %}
                        <i>Класс не назначен</i>
                    {% endif %}
                </p>
                <p>
                    {% if student.date_of_birth %}
                        {{ student.date_of_birth|date:"d.m.Y" }}
                    {% else %}
                        <i>Дата рождения не указана</i>
                    {% endif %}
                </p>
            <div>
        </main>
    </body>
</html>

students/templates/students/edit.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'students/style.css' %}" />
        <title>{{ student }} | Редактирование</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <h2 class="head_title">Редактирование ученика</h2>
            <form action="{% url 'students:edit_submit' student.id %}" method="post">
                {% csrf_token %}
                <table class="table_form">
                    <tr>
                        <td>Фамилия:</td>
                        <td><input name="last_name" value="{{ student.last_name }}" required /></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Имя:</td>
                        <td><input name="first_name" value="{{ student.first_name }}" required /></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Отчество:</td>
                        <td><input name="middle_name" value="{% if student.middle_name %}{{ student.middle_name }}{% endif %}" /></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Класс:</td>
                        <td><input name="group" list="groups_list" value="{% if student.group %}{{ student.group }}{% endif %}" /></td>
                        <td><i>(если класса с данным именем нет, он будет создан)</i></td>
                        <datalist id="groups_list">
                            {% if groups_list %}
                                {% for group in groups_list %}
                                    <option value="{{ group }}"></option>
                                {% endfor %}
                            {% endif %}
                        </datalist>
                    </tr>
                    <tr>
                        <td>Дата рождения:</td>
                        <td><input type="date" name="date_of_birth" value="{% if student.date_of_birth %}{{ student.date_of_birth|date:"Y-m-d" }}{% endif %}" /></td>
                        <td></td>
                    </tr>
                </table>
                <br />
                <input type="submit" value="Сохранить">
            </form>
        </main>
    </body>
</html>

students/templates/students/index.html
<!DOCTYPE html>
<html lang="ru-RU">
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'jquery/chosen/chosen.jquery.min.js' %}"></script>
        <script src="{% static 'script.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'jquery/chosen/chosen.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'students/style.css' %}" />
        <title>Ученики</title>
    </head>
    <body>
        <header>
            <a href="{% url 'students:index' %}">
                Ученики
            </a>
            <a href="{% url 'olymps:index' %}">
                Олимпиады
            </a>
        </header>

        <main>
            <a href="{% url 'students:add' %}"><button>Добавить одного</button></a>
            <br />
            <a href="{% url 'students:add_file' %}"><button>Добавить из файла</button></a>
            <h2 class="head_title">Все ученики</h2>
            {% if students %}
                <table class="list">
                    <thead>
                        <td>ID</td>
                        <td>Фамилия</td>
                        <td>Имя</td>
                        <td>Отчество</td>
                        <td>Класс</td>
                        <td>Дата рождения</td>
                    </thead>
                    {% for user in students %}
                        <tr class="list_item" onclick="document.location = '{% url 'students:detail' user.id %}'">
                            <td>{{ user.id }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.first_name }}</td>
                            <td>
                                {% if user.middle_name %}
                                    {{ user.middle_name }}
                                {% endif %}
                            </td>
                            <td>
                                {% if user.group %}
                                    {{ user.group }}
                                {% endif %}
                            </td>
                            <td>{{ user.date_of_birth|date:"d.m.Y" }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>Нет учеников.</p>
            {% endif %}
        </main>
    </body>
</html>